-- DATABASE CREATE AND CONFIG
DROP DATABASE IF EXISTS BASE_DE_SENHAS;
CREATE DATABASE BASE_DE_SENHAS DEFAULT CHARSET=utf8mb4;
USE BASE_DE_SENHAS;

-- USER CREATE AND CONFIG
DROP USER IF EXISTS 'read_user'@'localhost';
CREATE USER 'read_user'@'localhost' IDENTIFIED BY 'password_manager';
GRANT SELECT ON BASE_DE_SENHAS.* TO 'read_user'@'localhost';
FLUSH PRIVILEGES;

-- TABLE CREATE AND CONFIG
CREATE TABLE SISTEMAS (
    ID                INT PRIMARY KEY AUTO_INCREMENT,
    NOME_SISTEMA      VARCHAR(100) NOT NULL,
    TIPO_SISTEMA      VARCHAR(50)  NULL,
    PROTOCOLO_SERVICO VARCHAR(20)  NULL,
    PORTA             INT          NULL,
    LINK              VARCHAR(255) NULL,
    DESCRICAO         TEXT         NULL,
    DATA_CRIACAO      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_sistema_nome (NOME_SISTEMA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLE CREATE AND CONFIG
CREATE TABLE CREDENCIAIS (
    ID               INT PRIMARY KEY AUTO_INCREMENT,
    ID_SISTEMA       INT          NOT NULL,
    TIPO             VARCHAR(30)  NOT NULL,
    TIPO_SGBD        VARCHAR(50)  NULL,
    HOST             VARCHAR(150) NULL,
    DATABASE_NAME    VARCHAR(100) NULL,
    USUARIO          VARCHAR(150) NULL,
    SENHA            VARCHAR(255) NULL,
    OBSERVACAO       TEXT         NULL,
    DATA_CRIACAO     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_credencial_sistema FOREIGN KEY (ID_SISTEMA)
        REFERENCES SISTEMAS(ID) ON DELETE CASCADE,
    KEY idx_credencial_sistema (ID_SISTEMA),
    KEY idx_credencial_tipo (TIPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;